version: '3.1'

services:
  hibiscus-server:
    image: hibiscus_server
    #command: initdb # beim ersten Durchlauf mit MySQL muss einmal mit initdb die Datenbanktabellen angelegt werden.
    ports:
      - "8090:8080"
    environment:
      PASSWORD: foo
      DB_DRIVER: mysql
      DB_ADDR: db
      DB_NAME: hibiscus
      DB_USERNAME: hibiscus
      DB_PASSWORD: hibiscus
      USE_SSL: false
    depends_on: 
      - db
  db:
    container_name: hibiscus_db
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: hibiscus
      MYSQL_USER: hibiscus
      MYSQL_PASSWORD: hibiscus
    volumes:
      - db_data:/var/lib/mysql
    # optional:
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -prootpass | grep 'mysqld is alive' || exit 1"]

volumes:
  db_data:  
